version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=837726742550.dkr.ecr.us-east-1.amazonaws.com/petclinic
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker build -t petclinic .
      - docker tag petclinic:latest 837726742550.dkr.ecr.us-east-1.amazonaws.com/petclinic:latest
      - docker push 837726742550.dkr.ecr.us-east-1.amazonaws.com/petclinic:latest
artifacts:
    files: imagedefinitions.json
